-- Games: one row per room (code)
create table if not exists games (
  code text primary key,
  ticker text not null,
  created_at timestamptz default now()
);

-- Scores: one row per submission (global and per-game)
create table if not exists scores (
  id bigint generated by default as identity primary key,
  game_id text references games(code) on delete set null,
  name text not null default 'Player',
  score integer not null,
  created_at timestamptz default now()
);

create index if not exists scores_game_id_idx on scores(game_id);
create index if not exists scores_score_desc_idx on scores(score desc);

-- Allow anonymous access for game (use RLS in production)
alter table games enable row level security;
alter table scores enable row level security;

create policy "Allow read games" on games for select using (true);
create policy "Allow insert games" on games for insert with check (true);
create policy "Allow read scores" on scores for select using (true);
create policy "Allow insert scores" on scores for insert with check (true);
